name: Continuous Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  continuous-deployment:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: Create build version
        id: createbuildversion
        run:
          echo "::set-output name=buildversion::$(date +'%y.%m%d').${{ github.run_number }}"

      - name: Check build version
        run:
          echo "Using version ${{steps.createbuildversion.outputs.buildversion}}"

      - name: Generate app.ver
        run: |
          echo ${{steps.createbuildversion.outputs.buildversion}} >${GITHUB_WORKSPACE}\publish\app.ver
        shell: pwsh

      - name: Install necessary modules
        run: |
          Install-Module -Name PSScriptAnalyzer -Force
        shell: pwsh

      - name: Validate module definition
        run: |
          Test-ModuleManifest ${GITHUB_WORKSPACE}\src\adx-cicd-tools.psd1
        shell: pwsh

      - name: Linting & static analysis
        run: |
          Invoke-ScriptAnalyzer -Path ${GITHUB_WORKSPACE}\src -Recurse
        shell: pwsh

      - name: Test publishing processes
        env:
          POWERSHELLGALLERY_API_KEY: ${{ secrets.POWERSHELLGALLERY_API_KEY }}
        run: |
          $publishPath = ${GITHUB_WORKSPACE}\publish\adx-cicd-tools
          xcopy /frys ${GITHUB_WORKSPACE}\src "$publishPath\"
          Publish-Module -Path $publishPath -NuGetApiKey $env:POWERSHELLGALLERY_API_KEY -Verbose -WhatIf
        shell: pwsh

